backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    extension: "md"
    format: "frontmatter"
    files:
      - name: "home"
        label: "Home"
        file: "home.md"
        description: "General site settings"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
