backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
# publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "pages"
    label: "Pages"
    extension: "md"
    format: "frontmatter"
    files:
      - name: "home_en"
        label: "Home EN"
        file: "content/pages/home_en.md"
        description: "Home english"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
      - name: "home_fr"
        label: "Home FR"
        file: "content/pages/home_fr.md"
        description: "Home french"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
      - name: "about_en"
        label: "about EN"
        file: "content/pages/about_en.md"
        description: "about english"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - name: "about_fr"
        label: "about FR"
        file: "content/pages/about_fr.md"
        description: "about french"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Body"
            name: "body"
            widget: "markdown"
  - name: "articles_en"
    label: "Article in english"
    folder: "content/articles_en/"
    extension: "md"
    format: "frontmatter"
    create: true
    id: "{{id}}"
    identifier_field: id
    summary: "{{title}}"
    fields:
      - label: "Id"
        name: "id"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "articles_fr"
    label: "Article en français"
    folder: "content/articles_fr/"
    extension: "md"
    format: "frontmatter"
    create: true
    id: "{{id}}"
    identifier_field: id
    summary: "{{title}}"
    fields:
      - label: "Id"
        name: "id"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "events"
    label: "Evenements"
    folder: "content/events/"
    extension: "md"
    format: "frontmatter"
    create: true
    id: "{{id}}"
    identifier_field: id
    summary: "{{title}}"
    fields:
      - label: "Id"
        name: "id"
        widget: "string"
      - label: "Nom en français"
        name: "name_fr"
        widget: "string"
      - label: "Nom en anglais"
        name: "name_en"
        widget: "string"
      - label: "Lieu"
        name: "place"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Heure"
        required: false
        name: "hour"
        widget: "datetime"
        format: "HH:mm"
        dateFormat: false
        timeFormat: "HH:mm"
      - label: "Texte français"
        name: "body_fr"
        widget: "markdown"
      - label: "Texte anglais"
        name: "body_en"
        widget: "markdown"
